package Chapter_8_Exercises.Exercises.Eight_dot_2;

public class Notion_of_Package_Access {



/*
(Based on Section 8.14) Explain the notion of package access in Java.

THIS HAPPENS WHEN YOU DID NOT SPECIFY WHETHER THE CLASS IS PRIVATE OR PUBLIC OR PROTECTED BY NOT SPECIFYING THE
ACCESS MODIFIER. BEHIND THE SCENE, THIS MAKES THE CLASS ONLY ACCESSIBLE BY
 1. CLASSES INSIDE THE SAME PACKAGE WITH IT.


 Explain the negative aspects of package access.
NEGATIVE ASPECTS
    ACCESSIBILITY IS SCOPED TO THE PACKAGE AND SOME TIMES THAT IS NOT WHAT YOU WANT.
    IT IS NOT EXPLICIT OR CLEAR DUE TO THE LACK OF THE ACCESS MODIFIER TO LET THE DEVELOPER KNOW THE TYPE OF OF
    ACCESS OF MODIFIER THAT IT IS UNLESS THEY HAVE EXPERIENCE WITH SOMETHING SIMILAR.






 */


}
